// This file is auto-generated by internal/cmd/genoptions/main.go. DO NOT EDIT

package httprc

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestOptionIdent(t *testing.T) {
	require.Equal(t, "WithErrSink", identErrSink{}.String())
	require.Equal(t, "WithFetcherWorkerCount", identFetcherWorkerCount{}.String())
	require.Equal(t, "WithHTTPClient", identHTTPClient{}.String())
	require.Equal(t, "WithMinRefreshInterval", identMinRefreshInterval{}.String())
	require.Equal(t, "WithRefreshInterval", identRefreshInterval{}.String())
	require.Equal(t, "WithRefreshWindow", identRefreshWindow{}.String())
	require.Equal(t, "WithTransformer", identTransformer{}.String())
	require.Equal(t, "WithWhitelist", identWhitelist{}.String())
}
