// This file is auto-generated by internal/cmd/genoptions/main.go. DO NOT EDIT

package httprc

import (
	"time"

	"github.com/lestrrat-go/option"
)

type Option = option.Interface

type ConstructorOption interface {
	Option
	constructorOption()
}

type constructorOption struct {
	Option
}

func (*constructorOption) constructorOption() {}

type RegisterOption interface {
	Option
	registerOption()
}

type registerOption struct {
	Option
}

func (*registerOption) registerOption() {}

type identFetchWorkerCount struct{}
type identHTTPClient struct{}
type identMinRefreshInterval struct{}
type identRefreshInterval struct{}
type identRefreshWindow struct{}
type identTransformer struct{}

func (identFetchWorkerCount) String() string {
	return "WithFetchWorkerCount"
}

func (identHTTPClient) String() string {
	return "WithHTTPClient"
}

func (identMinRefreshInterval) String() string {
	return "WithMinRefreshInterval"
}

func (identRefreshInterval) String() string {
	return "WithRefreshInterval"
}

func (identRefreshWindow) String() string {
	return "WithRefreshWindow"
}

func (identTransformer) String() string {
	return "WithTransformer"
}

func WithFetchWorkerCount(v int) ConstructorOption {
	return &constructorOption{option.New(identFetchWorkerCount{}, v)}
}

func WithHTTPClient(v HTTPClient) RegisterOption {
	return &registerOption{option.New(identHTTPClient{}, v)}
}

func WithMinRefreshInterval(v time.Duration) RegisterOption {
	return &registerOption{option.New(identMinRefreshInterval{}, v)}
}

func WithRefreshInterval(v time.Duration) RegisterOption {
	return &registerOption{option.New(identRefreshInterval{}, v)}
}

func WithRefreshWindow(v time.Duration) ConstructorOption {
	return &constructorOption{option.New(identRefreshWindow{}, v)}
}

func WithTransformer(v Transformer) RegisterOption {
	return &registerOption{option.New(identTransformer{}, v)}
}
