// This file is auto-generated by internal/cmd/genoptions/main.go. DO NOT EDIT

package httprc

import (
	"time"

	"github.com/lestrrat-go/option"
)

type Option = option.Interface

type NewOption interface {
	Option
	newOption()
}

type newOption struct {
	Option
}

func (*newOption) newOption() {}

type RegisterOption interface {
	Option
	registerOption()
}

type registerOption struct {
	Option
}

func (*registerOption) registerOption() {}

type identHTTPClient struct{}
type identMinRefreshInterval struct{}
type identRefreshInterval struct{}
type identRefreshWindow struct{}

func (identHTTPClient) String() string {
	return "WithHTTPClient"
}

func (identMinRefreshInterval) String() string {
	return "WithMinRefreshInterval"
}

func (identRefreshInterval) String() string {
	return "WithRefreshInterval"
}

func (identRefreshWindow) String() string {
	return "WithRefreshWindow"
}

func WithHTTPClient(v HTTPClient) RegisterOption {
	return &registerOption{option.New(identHTTPClient{}, v)}
}

func WithMinRefreshInterval(v time.Duration) RegisterOption {
	return &registerOption{option.New(identMinRefreshInterval{}, v)}
}

func WithRefreshInterval(v time.Duration) RegisterOption {
	return &registerOption{option.New(identRefreshInterval{}, v)}
}

func WithRefreshWindow(v time.Duration) NewOption {
	return &newOption{option.New(identRefreshWindow{}, v)}
}
