name: Auto-Doc
on: 
  pull_request:
    branches:
      - v3
    types:
      - closed
  workflow_dispatch: {}

jobs:
  autodoc:
    runs-on: ubuntu-latest
    name: "Run commands to generate documentation"
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repositor
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Process markdown files
        run: |
          find . -name '*.md' | xargs perl tools/autodoc.pl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
