name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.24', '1.23' ]
    name: Go ${{ matrix.go }} test
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Check documentation generator
        run: |
          find . -name '*.md' | xargs env AUTODOC_DRYRUN=1 perl tools/autodoc.pl
      - name: Install Go stable version
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test -v -race -timeout=5m

