name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.24', '1.23' ]
    name: Go ${{ matrix.go }} test
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Check documentation generator
        run: |
          find . -name '*.md' | xargs env AUTODOC_DRYRUN=1 perl tools/autodoc.pl
      - name: Install Go stable version
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test -v -race -timeout=5m

