name: lint
on: [push]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.19]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.50.0
      - name: Run go vet
        run: |
          go vet ./...
